const SELECT_YEAR_ELEMENT = document.querySelector(`#year-control`);

const LOOP_ELEMENT = document.querySelector(`#loop-control`);

const NUMBER_OF_APPLICANTS = 10;

const DUMMY_DATA = {
  2000: [
    {applicant: "Bob", patents: 12},
    {applicant: "Robin", patents: 25},
    {applicant: "Anne", patents: 28},
    {applicant: "Mark", patents: 16},
    {applicant: "Joe", patents: 59},
    {applicant: "Eve", patents: 34},
    {applicant: "Karen", patents: 21},
    {applicant: "Kirsty", patents: 25},
    {applicant: "Chris", patents: 30},
    {applicant: "Lisa", patents: 47},
    {applicant: "Tom", patents: 5},
    {applicant: "Charles", patents: 77},
    {applicant: "Mary", patents: 29},
    {applicant: "Yolanda", patents: 87},
  ],
  2001: [
    {applicant: "Bob", patents: 23},
    {applicant: "Robin", patents: 234},
    {applicant: "Anne", patents: 567},
    {applicant: "Mark", patents: 231},
    {applicant: "Joe", patents: 345},
    {applicant: "Eve", patents: 567},
    {applicant: "Karen", patents: 39},
    {applicant: "Kirsty", patents: 90},
    {applicant: "Chris", patents: 80},
    {applicant: "Lisa", patents: 70},
    {applicant: "Tom", patents: 50},
    {applicant: "Charles", patents: 45},
    {applicant: "Mary", patents: 290},
    {applicant: "Yolanda", patents: 778},
  ],
  2002: [
    {applicant: "Bob", patents: 500},
    {applicant: "Robin", patents: 2500},
    {applicant: "Anne", patents: 300},
    {applicant: "Mark", patents: 1600},
    {applicant: "Joe", patents: 5900},
    {applicant: "Eve", patents: 1100},
    {applicant: "Karen", patents: 2100},
    {applicant: "Kirsty", patents: 250},
    {applicant: "Chris", patents: 800},
    {applicant: "Lisa", patents: 470},
    {applicant: "Tom", patents: 50},
    {applicant: "Charles", patents: 6700},
    {applicant: "Mary", patents: 2900},
    {applicant: "Yolanda", patents: 2200},
  ],
  2003: [
    {applicant: "Bob", patents: 500},
    {applicant: "Robin", patents: 46},
    {applicant: "Anne", patents: 56},
    {applicant: "Mark", patents: 84},
    {applicant: "Joe", patents: 590},
    {applicant: "Eve", patents: 324},
    {applicant: "Karen", patents: 434},
    {applicant: "Kirsty", patents: 23},
    {applicant: "Chris", patents: 800},
    {applicant: "Lisa", patents: 470},
    {applicant: "Tom", patents: 50},
    {applicant: "Charles", patents: 23},
    {applicant: "Mary", patents: 55},
    {applicant: "Yolanda", patents: 77},
  ],
  2004: [
    {applicant: "Bob", patents: 33},
    {applicant: "Robin", patents: 12},
    {applicant: "Anne", patents: 41},
    {applicant: "Mark", patents: 16},
    {applicant: "Joe", patents: 59},
    {applicant: "Eve", patents: 38},
    {applicant: "Karen", patents: 21},
    {applicant: "Kirsty", patents: 25},
    {applicant: "Chris", patents: 30},
    {applicant: "Lisa", patents: 47},
    {applicant: "Tom", patents: 5},
    {applicant: "Charles", patents: 13},
    {applicant: "Mary", patents: 29},
    {applicant: "Yolanda", patents: 120},
  ],
  2005: [
    {applicant: "Bob", patents: 50},
    {applicant: "Robin", patents: 44},
    {applicant: "Anne", patents: 30},
    {applicant: "Mark", patents: 160},
    {applicant: "Joe", patents: 455},
    {applicant: "Eve", patents: 445},
    {applicant: "Karen", patents: 67},
    {applicant: "Kirsty", patents: 25},
    {applicant: "Chris", patents: 80},
    {applicant: "Lisa", patents: 47},
    {applicant: "Tom", patents: 5},
    {applicant: "Charles", patents: 12},
    {applicant: "Mary", patents: 290},
    {applicant: "Yolanda", patents: 220},
  ],
};
